### ISSUE TITLE
OOM error when working with large wsis

### ISSUE THREAD

**Issue by clemsgrs** [mahmoodlab/TITAN#33]
I'm running into a CPU / CUDA out-of-memory error when using TITAN for slide-level inference on large whole-slide images.
The problem appears during the `encode_slide_from_patch_features` call.

I've investigated a bit, and the error seems cause by the construction of the attention bias in the `VisionTransformer`'s `forward_features` method:

```python3
f self.pos_encode_type == 'alibi':
...
attn_bias = self.get_alibi(w, h, bg_mask) if B == 1 else self.get_alibi(w, h)
attn_bias = attn_bias.repeat(x.shape[0], 1, 1, 1).type(x.dtype).to(x.device)
```

The call to `get_alibi(w, h)` attempts to build a full pairwise distance matrix with shape (w*h, w*h), which explodes in RAM usage for large grids. I've been able to get rid of the CPU OOM error by allocating more RAM, but then a CUDA OOM error appears as this very large tensor is sent to gpu via the `.to(x.device)` call.

What is your experience with running slide-level inference with TITAN on large WSIs?
Thank you for your help!

**Comment by clemsgrs** [comment]
a potential workaround is to shift to absolute position encoding, using `pos_encode_type = "abs"` instead of `pos_encode_type = "alibi"` in the [vision config](https://huggingface.co/MahmoodLab/TITAN/blob/main/config.json)
in my experiment, this results in OOM error gone
however, i'm not sure if TITAN was intended to be used with absolute position encoding.

**Comment by clemsgrs** [comment]
any update regarding this issue would be appreciated!

**Comment by andrewsong90** [comment]
Hi @clemsgrs 

Sorry for the delay in getting back to you.
Indeed, the `alibi` 2d positional encoding can be memory-wise cumbersome and we did experience OOM in some very large WSIs.
In the next version, we are trying to resolve this issue by providing more efficient implementation for attention mechanism (e.g. newer flash attention)

In the meantime, here is what I suggest
- Do not use `abs` positional encoding, since TITAN was not trained with absolute positional encoding. Its intention is to use 2D alibi encoding.
- If it's just inference, I would suggest moving everything to CPU (it seems you have sufficient CPU RAM to prevent OOM). So `x.device` would be CPU, rather than GPU in this case. In our experience, WSI inference with CPU is not too much slower compared to GPU-based inference (only during the training does it make huge difference).

Hope this helps!
Andrew
